### ISSUE TITLE
PyJulia does not work with Julia 1.0 & 0.7 with Python installed via Conda/Ubuntu/(what else?)

### ISSUE THREAD

**Issue by tkf** [JuliaPy/pyjulia#185]
I'm writing down the issue so that it is easy to find by the users.

At the moment, for PyJulia to load Julia >= 0.7, two conditions have to be met:

1. Python interpreter configured for PyCall.jl and Python interpreter used to import PyJulia have to have *exactly* identical paths.

2. The Python interpreter have to be dynamically linked (which is usually the case in Windows and macOS according to [this comment](https://github.com/JuliaPy/pyjulia/blob/25ab71cdc4fd17ef78127f3dd6e485d3efb8c327/julia/core.py#L246))

To check if the condition 2 is the case, check it with:

```console
$ ldd /usr/bin/python | grep libpython
        libpython3.7m.so.1.0 => /usr/lib/libpython3.7m.so.1.0 (0x00007f17c12c4000)
```

where `/usr/bin/python` is the appropriate Python interpreter.

If it does not print anything, you can't use PyJulia with this Python interpreter.

**Comment by tkf** [comment]
Yeah, I was surprised too.  I thought it was just conda (in which static compilation maybe makes sense).

**Comment by Hong-Xiang** [comment]
@tkf Thanks for your reply. But there are still some questions:
- Currently we do not have any method to call Julia in conda based/Ubuntu/Debian python3, right? Even dirty/tricky method would be helpful.   
- Could we use custom compiled python for it?  If true, is this a practical solution?
- Will this issue be solved in near future or we should not expect that?

Thanks.

**Comment by tkf** [comment]
I think there are three ways to use Python with Julia 1.0 on Ubuntu/Debian/etc. at the moment:

* If you just want to use your Python, you can import it from [PyCall.jl](https://github.com/JuliaPy/PyCall.jl) and call some functions.  See, e.g., https://github.com/tkf/IPython.jl/blob/d5b27ac6e38f1b96ba42099da1098975cdd8b9be/src/core.jl#L31 and https://github.com/tkf/IPython.jl/blob/d5b27ac6e38f1b96ba42099da1098975cdd8b9be/src/core.jl#L20 in `IPython.jl/src/core.jl`.
* If you just want an interactive Python session, you can use my [IPython.jl](https://github.com/tkf/IPython.jl) to drop into IPython through Julia REPL.
* If you want fully functional PyJulia in Python, one way to do it is though docker. Check out: https://github.com/tkf/docker-ipyjulia

> Will this issue be solved in near future

I think I know how to fix it #173. But likely not in next weeks. I can't grant anything :) If I were to do it I want to do it after dropping Julia 0.6 (which requires PyJulia to be released soon).

**Comment by tkf** [comment]
I made an experimental package `julia-venv`: https://github.com/tkf/julia-venv

It implements the private `DEPOT_PATH` hack mentioned in #173 but does so per-virtualenv basis.  This let us use different Python executables without recompiling PyCall.jl all the time.  On top of creating a private `DEPOT_PATH`, it installs a CLI `julia-venv` which acts like the normal `julia` interpreter (by invoking it via C API from Python).  This way, we can run PyCall.jl always in "PyJulia-mode" so that the issue with Python in Ubuntu/Debian and Conda can be avoided (https://github.com/tkf/julia-venv#how-it-works).  As a nice side-effect, you can also use PyCall.jl with different Python executable and different set of Python libraries.

**Comment by Hong-Xiang** [comment]
@tkf ，thanks for your awesome work. The new package works on Ubuntu 16.04 with anaconda. It really helps.

There are some minor suggestions (or some misunderstanding of me).

## third-party packages need to be re-compiled/re-installed

for test purpose, I test `from julia import NPZ`, while `NPZ` is already added in original julia environment. But it failed. 

and the following code works:
```
from julia import Pkg
Pkg.add("NPZ")
#... some install outputs
from julia import NPZ
data = NPZ.npzread("path")
```
It seems that pyjulia and julia of system is using different package cache? I think re-install packages is not a problem and it might be a valuable feature. I only suggest add some doc for this

## convenient broadcast call 
broadcast is commonly used in julia, but `Main.abs.([1,2,3])` is a `SyntaxError` in python.
in `README.md` of pyjulia, there is
```
Main.eval("sin.(xs)")
```
which seems that pyjulia will not expose broadcast method to python level. I'm not sure if I am right, but if it is true, I'm thinking is it possible to adding some special syntax like `Main.abs.broadcast([1,2,3])` or in short `Main.abs.b([1,2,3])` (although may introduce some confusing to `sum_b` for python version `sum!`).

## `InterruptException()` handling
When I press `ctrl-C` in python REPL, there would be a small problem.
If I'm using a pure python REPL, it should work like this
```
>>> # presss ctrl-C here
KeyboardInterrupt
>>> 
```
But in a python REPL which loaded julia, it would work like this:
```
>>> # press ctrl-C here
```
and nothing happens, after that if I enter next command
```
>>> # Ctrl - C, and nothing happens
>>> Main.xs = [1,2,3] # Enter, change line and type new command and Enter I got:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "(path_anaconda)/envs/juliaenv/lib/python3.6/site-packages/julia/core.py", line 140, in __setattr__
    self._julia.eval(setter)(value)
  File "(path_anaconda)/envs/juliaenv/lib/python3.6/site-packages/julia/core.py", line 606, in eval
    ans = self._call(src)
  File "(path_anaconda)/envs/juliaenv/lib/python3.6/site-packages/julia/core.py", line 562, in _call
    self.check_exception(src)
  File "(path_anaconda)/envs/juliaenv/lib/python3.6/site-packages/julia/core.py", line 589, in check_exception
    .format(exception, src))
julia.core.JuliaError: Exception 'InterruptException' occurred while calling julia code:

            PyCall.pyfunctionret(
                (x) -> eval(Main, :(xs = $x)),
                Any,
                PyCall.PyAny)
```
It seems the `InterruptException` is send to julia in one delayed statement?

**Comment by tkf** [comment]
Actually, `julia-venv` probably still doesn't work with Conda (and probably also with Ubuntu): https://github.com/tkf/julia-venv/pull/2

@Hong-Xiang Hey, thanks for the feedback. Are you using `julia-venv` in Ubuntu or Debian?  Did it actually work?

> I think re-install packages is not a problem and it might be a valuable feature.

Yeah, something like `virtualenv`'s `--system-site-packages` would be nice.  I actually did that in first versions but stopped doing that since I encountered with some quirks in `julia`'s package handling.  It it actually as "easy" as replacing [`depots = filter(!isequal(default_depot1), __py_julia_venv_orig_DEPOT_PATH)`](https://github.com/tkf/julia-venv/blob/7aed5996a684e8ea377067e4da632eb12526ecf1/src/julia_venv/startup.jl#L10-L14) with `depots = copy(__py_julia_venv_orig_DEPOT_PATH)`.

> convenient broadcast call

I started experimenting more numpy-like interface on top of PyJulia (i.e., broadcast operations on arrays by default):

https://ipyjulia-hacks.readthedocs.io/en/latest/

Not sure if it is suitable for PyJulia, though.

But if you want to leverage Julia, I think it's better to just use Julia syntax.  If you don't want to use global variable (of course), you can do:

```python
Main.eval("(xs) -> sin.(exp.(xs) .+ 1)")(xs)
```

or equivalently

```python
Main.eval("(xs) -> @. sin(exp(xs) + 1)")(xs)
```

Unlike `numpy.exp` etc., it doesn't allocate intermediate arrays.


> `InterruptException`

Hmm... I didn't notice that. But yes, I can reproduce it. Actually, I just noticed that it's reported in #189.  Let's track the issue there.

It looks like IPython 7 (development version) handle ctrl-C differently and it doesn't have this problem.  I've been using it so I didn't notice the problem.

**Comment by tkf** [comment]
Thanks. Interesting... Actually, the problem I thought I had was already fixed https://github.com/tkf/julia-venv/pull/2. My guess was that it was some kind of IO caching issue (compilation file was not properly written before exiting the problem). It then maybe explains why it's machine-dependent.

Anyway, I'm glad that it worked in your machine!

**Comment by tkf** [comment]
For Ubuntu/Debian users, probably the cleanest and relatively easy way to use PyJulia at the moment is to install (build) Python using [pyenv](https://github.com/pyenv/pyenv).  But you need to [pass `--enable-shared` manually](https://github.com/pyenv/pyenv/issues/65#issuecomment-30998608).

```console
$ PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.6.6
Downloading Python-3.6.6.tar.xz...
-> https://www.python.org/ftp/python/3.6.6/Python-3.6.6.tar.xz
Installing Python-3.6.6...
Installed Python-3.6.6 to /home/takafumi/.pyenv/versions/3.6.6

  200.54s user 16.69s system 271% cpu 1:20.10 total
$ ldd ~/.pyenv/versions/3.6.6/bin/python3.6
        linux-vdso.so.1 =>  (0x00007fff6933c000)
        libpython3.6m.so.1.0 => /home/takafumi/.pyenv/versions/3.6.6/lib/libpython3.6m.so.1.0 (0x00007fca44c8b000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fca44a6e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fca446a4000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fca444a0000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fca4429d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fca43f94000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fca451c0000)
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

**Comment by tkf** [comment]
Or you can switch to Arch Linux :laughing:

It uses `--enable-shared`: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/python&id=68e188a1f975dcc6798072bcda4ef35abfe162ed#n57

**Comment by tkf** [comment]
@ExpandingMan @mprogram So it turned out static linking is just the default behavior of Python's `./configure` script (see my message above https://github.com/JuliaPy/pyjulia/issues/185#issuecomment-420521153).  I guess Debian is not doing anything particularly evil here.

**Comment by mprogram** [comment]
Thanks, @tkf for your last two comments. I'm a fan of deb-based system and my thought would be that Debian needs to look at those. If I'll be up to recompile Python (for the sake of optimization with MKL, for example as Julia does), I would include the `--enable-shared` option in my build.

**Comment by tkf** [comment]
@mprogram It looks like pyenv does something more than passing `--enable-shared` to `./configure`:

* https://github.com/pyenv/pyenv/tree/master/plugins/python-build#building-with---enable-shared
* https://github.com/pyenv/pyenv/blob/5603eb51c93bf053f2b03e3d80a9d0be62dcdeec/plugins/python-build/bin/python-build#L2056

I didn't check if `./configure --enable-shared` was enough when building without `pyenv`.

**Comment by ExpandingMan** [comment]
This problem is not going to go away, Debian is not going to change it and lots and lots of people are going to try this as debian distros are the most popular (though I prefer Arch I still have to use them often myself).  My first question is how other languages solve this problem.  We can't be the first people ever to want to use a dynamically linked Python executable.  It would be good to see how Scala and Java solve this, though I haven't started looking yet.

I think at a minimum what we need is a very clear set of the simplest possible steps that one would take to get `pyjulia` running on debian in a very visible location right in the packages readme or documentation.  Thanks to @tkf to taking the first steps to this with his pyenv setup, I'm going to try it myself when I get a chance.

**Comment by tkf** [comment]
Yeah "switch to Arch Linux" was rather a joke... :wink:  It definitely is the biggest TODO in this package to support Debian family out-of-the-box.

> My first question is how other languages solve this problem.

I don't think the question is *how* to solve the problem. In principle there is a straightforward solution: just compile different cache of PyCall.jl and all other packages depending on it to different files.  For example, here is an idea to implement it: https://github.com/JuliaLang/julia/issues/27418#issuecomment-417826061.  The question is *when* that happens.  Or maybe it's more like *if* we can convince Julia core devs to include enough features required by PyJulia.

Until then, here is yet another solution: #200.  The idea is to bundle `python-jl` executable in PyJulia package which can be used to run your Python script instead of the usual `python` executable.

**Comment by ExpandingMan** [comment]
I think I'm rather confused about what the issue is here.  I thought the problem was that since the debian Python binary is statically linked, using `libpython` doesn't do you any good because you can't interact with the process started by `python`.  What I don't understand is what this has to do with the pre-compile process on the Julia side.  I would think that `pyjulia` is just talking to the `julia` process with `libjulia` and that you'd be perfectly able to use everything that was already precompiled for your regular Julia process.  Care to clarify?  (reading this thread did not clear it up for me)

**Comment by tkf** [comment]
> I thought the problem was that since the debian Python binary is statically linked, using libpython doesn't do you any good because you can't interact with the process started by python.

You can interact with C API of statically linked `python`.  For example, Python itself provides [`ctypes.pythonapi`](https://docs.python.org/3/library/ctypes.html) for such purpose.  Actually, `python` statically linked to `libpython` worked in `julia` 0.6 because it was easier to monkey-patch precompilation mechanism of `julia` 0.6.

The reason why it's related to Julia's precompilation mechanism is explained in [`julia/fake-julia/README`](https://github.com/JuliaPy/pyjulia/tree/f7a552d2eabbb5045c7182ba056d0867c05830f9/julia/fake-julia).  If you look at [this `if` block in `src/startup.jl` in `PyCall.jl`](https://github.com/JuliaPy/PyCall.jl/blob/0f685cf02b6214ffc40b0aba7ab657749d587f5a/src/startup.jl#L113-L139), you can see that it generates different macros depending on libpython is statically linked or not (`libpython === nothing` or not).  This `if` block is run at compile time and those macros are used all over the places so the functions in `PyCall.jl` becomes incompatible for the program statically linked to libpython (e.g., `python` in Ubuntu) and the program dynamically linked libpython (`julia`).  Apparently defining those different set of macros was important for improving the load time of `PyCall.jl` (https://github.com/JuliaPy/PyCall.jl/issues/167) so I guess we can't do the branching at runtime in `PyCall.jl` (I'm mentioning it since that was my question: https://github.com/JuliaPy/PyCall.jl/issues/528).

**Comment by tkf** [comment]
I merged a workaround for statically linked Python #200.  Basically, you "just" need to run `python-jl script.py` (notice the **`-jl`** suffix) instead of `python script.py` if you use Debian or conda.  You can try it by:

```
pip install https://github.com/JuliaPy/pyjulia/archive/master.zip#egg=julia
```

**Comment by ExpandingMan** [comment]
Awesome job!  Thanks so much for your work on this.  This was a really awkward problem in which we were basically just getting screwed by the distros (and sadly some of the most important ones) and there was really never going to be a perfect solution, this seems to be about the best we'll be able to do with the situation we've been put in.

If you could, I think it would be really great if you could explain this as much as possible in the README (I won't offer to do it myself since I'm not sure I fully understand what you did yet).

Thanks again!

**Comment by tkf** [comment]
Yep, README is the only blocker before the release ATM.

**Comment by bstellato** [comment]
Guys I might have found a solution to this! If you install python from conda-forge there is no need for `python-jl`. Try this

```
conda install -c conda-forge python
```

```
python -c "import julia.Main"
```
It should work. See https://github.com/JuliaPy/pyjulia/pull/212#issuecomment-433229160

**Comment by ExpandingMan** [comment]
How is that a better solution than `python-jl`?  Personally I'd prefer `python-jl` running on the system Python binaries, but I suppose it's nice to have as many options as possible.

**Comment by bstellato** [comment]
If you are using Conda you are already not using the system Python binaries. In the other cases, I agree there is still need for `python-jl`. Also, there can still be issues with `python-jl` https://github.com/JuliaPy/pyjulia/issues/208.

**Comment by ExpandingMan** [comment]
Agreed, let's just aim to document as many options as possible and people will be able to select whatever solution works best for them.

**Comment by tkf** [comment]
@bstellato Thanks!.  This is a good news!  So I guess `conda-forge` distributes a Python executable dynamically linked to libpython.  I'll add it to the documentation.

@ExpandingMan Yeah, I think `python-jl` should stay.  Another benefit of `python-jl` is that signal handler is slightly well behaved this way (libjulia "steals" signal handler from `python` #211).

**Comment by tkf** [comment]
It's a bit strange. 3.7.0 from conda-forge is statically linked:

```console
$ conda create --prefix conda-forge-python conda-forge::python
...
The following NEW packages will be INSTALLED:
...
    python:          3.7.0-h5001a0f_4        conda-forge
...
$ conda-forge-python/bin/python
Python 3.7.0 | packaged by conda-forge | (default, Sep 30 2018, 14:56:18)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
$ ldd conda-forge-python/bin/python
        linux-vdso.so.1 (0x00007ffec5dce000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f86eb290000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f86eb28b000)
        libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f86eb286000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f86eb27c000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f86eb0f7000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f86eaf33000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f86eb2e4000)
$ conda-forge-python/bin/python -c 'from julia.find_libpython import linked_libpython; print(linked_libpython())'
None
```

But `conda-forge::python=3.6` _is_ dynamically linked.

```console
$ rm -r conda-forge-python
$ conda create --prefix conda-forge-python conda-forge::python=3.6
...
The following NEW packages will be INSTALLED:
...
    python:          3.6.6-h5001a0f_3        conda-forge
...
$ ldd conda-forge-python/bin/python
        linux-vdso.so.1 (0x00007ffff0f7e000)
        libpython3.6m.so.1.0 => /home/takafumi/repos/pyjulia/conda-forge-python/bin/../lib/libpython3.6m.so.1.0 (0x00007f1f758a8000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f1f75856000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f1f75851000)
        libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f1f7584c000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f1f75842000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f1f756bd000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f1f754f7000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f1f75de7000)
$ conda-forge-python/bin/python -c 'from julia.find_libpython import linked_libpython; print(linked_libpython())'
/home/takafumi/repos/pyjulia/conda-forge-python/lib/libpython3.6m.so.1.0
```

**Comment by bstellato** [comment]
Version 3.7.0 is still dynamically linked for me on mac os.

```
conda create -n testpyjulia37 conda-forge::python
conda activate testpyjulia37
ldd $(which python)
```

I get
```
/Users/xxx/miniconda3/envs/testpyjulia37/bin/python:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1153.18.0)
	@rpath/libpython3.7m.dylib (compatibility version 3.7.0, current version 3.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

**Comment by tkf** [comment]
Interesting. I asked the question in conda-forge: https://github.com/conda-forge/python-feedstock/issues/222

**Comment by tkf** [comment]
I just merged #256 to master.  I think PyJulia is now usable with many CPython executables if you can compile a custom system image with `python3 -m julia.sysimage` command.  The bonus point is that this makes PyJulia startup virtually instantaneous.  See: https://pyjulia.readthedocs.io/en/latest/sysimage.html

**Comment by tk3369** [comment]
Hi @tkf - it's annoying having to deal with [this issue](https://pyjulia.readthedocs.io/en/latest/troubleshooting.html). Do you know which Linux distro (ideally docker container) that provides a dynamically linked Python?

**Comment by tkf** [comment]
It works in Arch Linux :)

IIRC, the official `python` docker works. It's a bit old, but here is an example for setting up PyJulia in Docker: https://github.com/tkf/docker-pyjulia

Also, just FYI, I started working on compile-time preference integration for PyCall https://github.com/JuliaPy/PyCall.jl/pull/835. _If_ it works as I expected, PyJulia should just work without any hacks in Julia 1.6 and above. Obviously, there are still some unknowns as I haven't finished implementing all. So, let's see ;)

**Comment by Ge0rges** [comment]
What's the status of this issue? I am trying to run PyJulia in Ubuntu 22 but python is statically linked.

**Comment by mkitti** [comment]
I think that might be a question for conda-forge. If you are going to compile it yourself, do you actually need conda though?

Perhaps we could use https://github.com/JuliaBinaryWrappers/Python_jll.jl

**Comment by traversaro** [comment]
Just FYI, it seems that also `python-build-standalone` is considering switching to static builds of python for performance gains: https://github.com/astral-sh/python-build-standalone/pull/540 .

**Comment by traversaro** [comment]
> Just FYI, it seems that also `python-build-standalone` is considering switching to static builds of python for performance gains: [astral-sh/python-build-standalone#540](https://github.com/astral-sh/python-build-standalone/pull/540) .

Ah, it seems that this package is now deprecated, so it may not be a big problem: https://github.com/JuliaPy/pyjulia/pull/556 .
